version: '3.2'

services:
  zoo1:
    image: zookeeper
    restart: 'no'
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181  
        
  kafka1:
    image: wurstmeister/kafka
    restart: "no"
    ports:
      - '9093:9093'
    environment:
      KAFKA_LISTENERS: INSIDE://kafka1:9092,OUTSIDE://kafka1:9093
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9092,OUTSIDE://127.0.0.1:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_CREATE_TOPICS: 'Topic1:1:1'
      KAFKA_BROKER_ID: 1
    depends_on:
      - zoo1
    volumes:
      - ./kafka/broker1/kafka-logs:/kafka
    
  kafka2:
    image: wurstmeister/kafka
    restart: "no"
    ports:
      - '9094:9094'
    environment:
      KAFKA_LISTENERS: INSIDE://kafka2:9092,OUTSIDE://kafka2:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:9092,OUTSIDE://127.0.0.1:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_BROKER_ID: 2
    depends_on:
      - zoo1
    volumes:
      - ./kafka/broker2/kafka-logs:/kafka